# **Data Loading**

Data frames can be downloaded at https://grouplens.org/datasets/movielens/32m/, then save them to the directory you prefer. We will focus only on movies.csv and ratings.csv.

In [1]:
import pandas as pd

## **Movies DF**

Movie information is contained in the file movies.csv. Each line of this file after the header row represents one movie.
Movie titles are entered manually or imported from https://www.themoviedb.org/, and include the year of release in parentheses. Errors and inconsistencies may exist in these titles.

Genres are a pipe-separated list, and are selected from the following:
Action
Adventure
Animation
Children's
Comedy
Crime
Documentary
Drama
Fantasy
Film-Noir
Horror
Musical
Mystery
Romance
Sci-Fi
Thriller
War
Western
(no genres listed)

In [3]:
movies = pd.read_csv('movies.csv')
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

## **Ratings DF**

All ratings are contained in the file ratings.csv. Each line of this file after the header row represents one rating of one movie by one user.
The lines within this file are ordered first by userId, then, within user, by movieId.

Ratings are made on a 5-star scale, with half-star increments (0.5 stars - 5.0 stars).

Timestamps represent seconds since midnight Coordinated Universal Time (UTC) of January 1, 1970. We will discard this column as we don't care about time. However, it could be the topic of further research to also understand seasonality, trends...

In [4]:
ratings = pd.read_csv('ratings.csv')
ratings.head()

   userId  movieId  rating  timestamp
0       1       17     4.0  944249077
1       1       25     1.0  944250228
2       1       29     2.0  943230976
3       1       30     5.0  944249077
4       1       32     5.0  943228858